name: Deploy Solution BasicWebPartCICD
trigger:
  branches:
    include:
      - main
  paths:
    include:
    - '1_22_0_Beta3/02Pipelines/01BuildDeploy/BasicWebPartCICD22'
pool:
  vmImage: ubuntu-latest
variables:
  - group: Test
  - name: PackageName
    value: basic-web-part-cicd-22.sppkg
  - name: NodeVersion
    value: 22.x
  - name: CertificateSecureFileName
    value: Test.pfx  
  - name: WorkingDir
    value: '1_22_0_Beta3/02Pipelines/01BuildDeploy/BasicWebPartCICD22'
stages:
  - stage: Build_and_Deploy
    jobs:
      - job: Build_and_Deploy
        steps:
          - task: NodeTool@0
            displayName: Use Node.js
            inputs:
              versionSpec: $(NodeVersion)
          - task: NodeTool@0
            displayName: Use Node.js
            inputs:
              versionSpec: $(NodeVersion)
          - task: DownloadSecureFile@1
            displayName: Download PFX Certificate
            name: certificateFile
            inputs:
              secureFile: $(CertificateSecureFileName)
          - task: Npm@1
            displayName: Run npm install
            inputs:
              command: install
              workingDir: '$(WorkingDir)'
          - task: Npm@1
            displayName: Run npm package-solution-prod
            inputs:
              command: custom
              customCommand: run package-solution-prod
              workingDir: '$(WorkingDir)'
          - task: Npm@1
            displayName: Install CLI for Microsoft 365
            inputs:
              command: custom
              verbose: false
              customCommand: install -g @pnp/cli-microsoft365
          - script: >
              
              m365 login --authType certificate --certificateFile '$(certificateFile.secureFilePath)' --password '$(CertificatePassword)' --appId '$(CDPipeline_EntraID)' --tenant '$(CDPipeline_TenantID)' 

              m365 spo set --url '$(SharePointBaseUrl)' 

              m365 spo app add --filePath '$(Build.SourcesDirectory)/$(WorkingDir)/sharepoint/solution/$(PackageName)' --overwrite 

              m365 spo app deploy --skipFeatureDeployment --name '$(PackageName)' --appCatalogScope 'tenant'
            displayName: CLI for Microsoft 365 Deploy App
