name: Deploy Solution BasicWebPartCICD
on:
  push:
    branches:
      - main
    paths:
      - 'ESPC2025/1_21_1/02Pipelines/01BuildDeploy/BasicWebPartCICD/**'
  workflow_dispatch: null
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NodeVersion: 22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Use Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ env.NodeVersion }}
      - name: Run npm ci
        run: npm ci
      - name: Bundle & Package
        run: |
          gulp bundle --ship
          gulp package-solution --ship
      - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v2.2.4
        with:
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          APP_ID: ${{ secrets.APP_ID }}
          TENANT: ${{ secrets.TENANT_ID }}
      - name: CLI for Microsoft 365 Deploy App
        uses: pnp/action-cli-deploy@v4.0.0
        with:
          APP_FILE_PATH: sharepoint/solution/basic-web-part-cicd.sppkg
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true
